### 배열의 생성

In [4]:
import numpy as np

In [5]:
# 랜덤값으로 배열 생성하기
# np.random.random(배열의 크기)
# 0~1 사이의 값을 가지는 배열을 생성
np.random.rand(2,3)

array([[0.36595402, 0.46166289, 0.98755778],
       [0.57589589, 0.71950136, 0.99525466]])

In [6]:
# 내가 원하는 범위만큼의 랜덤값 생성
# np.random.randint(시작수, 끝수+1, size=배열의크기)
np.random.randint(2,11, size=(2,3))


array([[8, 2, 8],
       [2, 4, 3]])

In [7]:
# 2부터 10까지의 랜덤한 실수값으로 이루어진 (5,4)크기의 배열 생성
# 정수+실수=실수
float=np.random.rand(5,4)
float

array([[0.63347923, 0.70604692, 0.65269292, 0.71757931],
       [0.82732308, 0.67165373, 0.48424116, 0.86115172],
       [0.00644656, 0.63902198, 0.30862286, 0.94015901],
       [0.4180796 , 0.28102254, 0.0577825 , 0.90597417],
       [0.38945066, 0.38413544, 0.64541866, 0.91108519]])

In [8]:
num=np.random.randint(2,10,size=(5,4))
num

array([[5, 5, 5, 6],
       [4, 4, 8, 6],
       [5, 9, 7, 3],
       [6, 4, 2, 2],
       [9, 2, 4, 8]])

In [9]:
result=num+float
result

array([[5.63347923, 5.70604692, 5.65269292, 6.71757931],
       [4.82732308, 4.67165373, 8.48424116, 6.86115172],
       [5.00644656, 9.63902198, 7.30862286, 3.94015901],
       [6.4180796 , 4.28102254, 2.0577825 , 2.90597417],
       [9.38945066, 2.38413544, 4.64541866, 8.91108519]])

In [10]:
# 타입 변경하기
# asrtpe(변경할 타입)
float.astype('int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 배열의 기능

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 인덱싱
# []
# 2차원에서 0번째 출력
arr[0]

array([1, 2, 3])

In [13]:
arr[0,1]

2

In [14]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1[3:8]

array([3, 4, 5, 6, 7])

In [16]:
# 0~49 배열 출력

In [17]:
arr2=np.arange(50)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
# arr2를 (5,10)으로 재 배열하기
# reshape
# 바뀌기 전과 후의 데이터 수가 똑같아야함.
# 출력을 진행하고 저장은 따로 진행하지 않음.
# 저장하고 싶을 시 변수 생성 후 따로 저장해야함.
arr3= arr2.reshape(5,10)

In [20]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
# 2차원 슬라이싱
arr3[0:2,0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
#인덱싱 -> 첫번째 수 :  끝수 +1
# : 끝수+1 = 처음부터 끝수까지
# 시작수 : = 시작수부터 끝까지
# : = 처음부터 끝까지

In [43]:
arr3[:5,0:1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [44]:
arr3[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [47]:
# 파일 불러오기
data = np.loadtxt("height_weight.txt",delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [91]:
#bmi 알아보는 문제 
# 키_m = 키_cm/100
# 몸무게 = data[1]
# 몸무게 / (키_m * 키_m )
result=data[1,0:]/((data[0,0:]**2)/10000)
result

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

# Boolean 인덱싱

## True는 출력하고 False는 출력하지 않음

## 인덱싱을 진행할때 값의 개수가 동일한 수의 불리언 데이터 필요

## 원하는 조건에 맞는 값을 출력하는 방법


In [113]:
arr3=np.array([10,20,15,30])
arr3

array([10, 20, 15, 30])

In [101]:
bol = np.array([True,False,True,False])
bol

array([ True, False,  True, False])

In [102]:
arr3[bol]

array([10, 15])

In [104]:
arr3[arr3<17]

array([10, 15])

#arr3 20인 값만 출력

In [112]:
print(arr3==20)
arr3[arr3==20]

[False  True False False]


array([20])

In [ ]:
# numpy에서 사용하는 연산 함수

In [ ]:
# 1~9까지 랜덤한 정수가 담긴 2,5 크기의 배열 생성.

In [116]:
arr1=np.random.randint(1,10,size=(2,5))
arr1

array([[5, 1, 1, 9, 2],
       [6, 5, 6, 6, 4]])

In [ ]:
# 배열 안에 있는 값 더하기
# np.sum (배열값, axis)

In [120]:
np.sum(arr1, axis=1)

array([18, 27])

In [ ]:
# 배열 안에 있는 값의 평균
# np,mean(배열값)

In [128]:
np.mean(arr1, axis=1)

array([3.6, 5.4])

## 영화 평점 데이터분석

In [131]:
# 데이터 타입 변경
# dtype
data = np.loadtxt('ratings.txt',delimiter="::", dtype='int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [132]:
# 1.전체 평점 구하기
# 2. 각 사용자별 평점 평균 구하기
# 3. 각 사용자별 평균 평점이 4점 이상인 사용자 구하기

In [138]:
# 1. 전체 평점 구하기
np.mean(data[:,2])

3.581564453029317

In [179]:
# 리스트에 [사용자, 사용자의 평균]
# 1번 사용자의 평점 평균 구하기 > 1~6040
#data[:,0] 전체 정보에서 id값만 출력
#전체 정보에서 id값이 1인 값만 출력
user_list=[]
user=data[data[:,0]==1]
user_list.append( [1, np.mean(user[:,2])])
user_list
# 출력된 값에서 평점값만 추출한후 평균 구하기

[[1, 4.188679245283019]]

In [190]:
# 2. 각 사용자별 평점 평균이 4점 이상인 사용자 구하기